### ISSUE TITLE
Cannot handle spaces in filenames

### ISSUE THREAD

**Issue by mbeynon-galois** [unidoc/unipdf-cli#56]
Merging two PDF files, one of which has spaces in the name:

# backslash escaped on command line ...
$ unipdf merge output.pdf part1.pdf part\ two\ report.pdf
Could not merge the input files: open part: no such file or directory

# enclosed in double quotes ...
$ unipdf merge output.pdf part1.pdf "part two report.pdf"
Could not merge the input files: open part: no such file or directory

I was forced to rename the input file to be "part_two_report.pdf" for it to work properly.  This should be an easy fix to not assume filenames won't have spaces in the name.

**Comment by kellemNegasi** [comment]
Hi @mbeynon-galois, thank for reporting this issue. We have tested this using the latest version of unipdf-cli ([v0.6.0](https://github.com/unidoc/unipdf-cli/releases/tag/v0.6.0)) and it doesn't exist anymore.  So we are closing it as fixed. Feel free to reopen it if you are still experiencing the same issue on your side.
