### ISSUE TITLE
Unable to use offline key with compiled binary

### ISSUE THREAD

**Issue by ARolek** [unidoc/unipdf-cli#57]
I just tried following your blog post, [Compressing and Optimizing PDFs in Pure Golang using UniPDF](https://unidoc.io/post/compressing-and-optimizing-pdfs-golang/) using a compiled binary with my offline key. For example:

```console
UNIDOC_LICENSE_FILE="unidoc_license.key" UNIDOC_LICENSE_CUSTOMER=<customer_name> unipdf license_info
```

And I get the following output:

```console
License: License Id:
Customer Id:
Customer Name: Unlicensed
Tier: unlicensed
Created At: 30 August 2023 at 17:23 UTC
Expires At: Never
Creator:  <>
```

The keys I'm providing are used in production so I know they're correct. I then dug into your source code and I found the bug:

https://github.com/unidoc/unipdf-cli/blob/b3344a326636cb1bf0f1466c71375c7931d7792b/pkg/pdf/pdf.go#L17-L25

If you look at line 24, the customer name is hard coded as an empty string. Change that line to pass the `customer` variable and everything works.

**Comment by sampila** [comment]
Hi @ARolek,

Thank you for posting this issue and provide the solution.

We opened the PR based on your solution https://github.com/unidoc/unipdf-cli/pull/58.

Best regards

**Comment by sampila** [comment]
Hi @ARolek 

As the PR is merged to the master branch, we closing this issue.

Best regards
