### ISSUE TITLE
README has the wrong link

### ISSUE THREAD

**Issue by deon-gracias** [unidoc/unipdf-cli#59]
In the readme the https://github.com/unidoc/unipdf-cli instead of https://github.com/unidoc/unipdf.

I know its a small issue and unimportant just wanted to notify.

**Comment by sampila** [comment]
Hi @deon-gracias 

Thanks for letting us know, we created PR to fix this https://github.com/unidoc/unipdf-cli/pull/60

Best regards,

**Comment by sampila** [comment]
Readme.md link is fixed, now closing this issue.
