### ISSUE TITLE
Feature Request: Organize PDF

### ISSUE THREAD

**Issue by deon-gracias** [unidoc/unipdf-cli#61]
I thought a cool feature would be to organize pdfs, since I use it on [ilovepdf.com](https://www.ilovepdf.com/) a lot. So I wrote this function from looking at some functions in the codebase.

The below code simply uses the existing split and merge functions to organize the pdfs.

I couldn't get it to run since I don't have a key to the product and I don't work at a company.

I hope I can contribute to the repo by making a pull request I can work on this feature. I wanted to create a function for it in the `pkg` folder. But I'm not sure of the behavior of the program since I have not been able to get it run due to the license.

```go
var organizeCmd = &cobra.Command{
	Use:                   "organize [FLAG]... INPUT_FILE OUTPUT_FILE [PAGES]",
	Short:                 "organize PDF files",
	Long:                  organizeCmdDesc,
	Example:               organizeCmdExample,
	DisableFlagsInUseLine: true,
	Run: func(cmd *cobra.Command, args []string) {
		inputPath := args[0]
		outputPath := args[1]
		password, _ := cmd.Flags().GetString("password")

		// Parse page range.
		var err error
		var pages []int

		if len(args) > 2 {
			if pages, err = parsePageRange(args[2]); err != nil {
				printUsageErr(cmd, "Invalid page range specified\n")
			}
		}

		splitFiles := make([]string, len(pages), len(pages))
		for _, page := range pages {
			temporaryFilePath := "./tmp/" + inputPath + "-" + strconv.Itoa(page)
			err = pdf.Split(inputPath, temporaryFilePath, password, []int{page})

			if err != nil {
				printErr("Error: %v\n", err)
			}
		}

		err = pdf.Merge(splitFiles, outputPath)
		if err != nil {
			printErr("Error: %v\n", err)
		}

		fmt.Printf("Successfully organized file %s\n", inputPath)
		fmt.Printf("Output file saved to %s\n", outputPath)
	},
	Args: func(cmd *cobra.Command, args []string) error {
		if len(args) < 2 {
			return errors.New("must provide at least the input and output files")
		}

		return nil
	},
}
```

**Comment by sampila** [comment]
Hi @deon-gracias,

Thanks for the suggestion and you can get free 100 credits from registering at [https://cloud.unidoc.io](https://cloud.unidoc.io) so you make your code run

**Comment by deon-gracias** [comment]
I worked on this feature on my [fork](https://github.com/deon-gracias/unipdf-cli). 
[This](https://github.com/deon-gracias/unipdf-cli/commit/3898c2938786d339d44b7affb4becfddfc704452#diff-49d35176da995ec8a39c5163e6743995024229fdd0647b887e888f8929133284) is the commit for the changes for adding the feature.

If you wish to incorporate, please let me know if I should submit a pull request.

Here are some of the screenshots of the working.

![image](https://github.com/user-attachments/assets/7edff727-461e-43ef-9751-71d4fcb7ef9c)
![image](https://github.com/user-attachments/assets/c8ae5bcb-c2cc-4a72-9af4-0cc51699a5f9)
![image](https://github.com/user-attachments/assets/c87b1bbd-afb5-46bf-9ccd-d7c17ca08c45)

**Comment by sampila** [comment]
Hi @deon-gracias,

Yes you can upon up the PR, we will reviews and adjust your PR later if needed to match our code standard.

Thanks for your contribution.

**Comment by deon-gracias** [comment]
Opened a [pull request](https://github.com/unidoc/unipdf-cli/pull/64)
